### PR TITLE
fontconfig: update to version 2.13.94

### PR DESCRIPTION
**Pull request by danyeaw**

### CODE REVIEW

**Comment by nacho** [comment]
wow, they ported it to meson? I am though a bit hesitant to update to an unstable version...

**Comment by danyeaw** [comment]
@nacho I saw that Arch was using the [development version](https://archlinux.org/packages/extra/x86_64/fontconfig/) as their main package version, so I figured it was stable enough for general use. Getting rid of 5300 lines of patches enticed me as well 😄. If we want to wait to 2.13.2 to be released, I would be OK with that as well. What do you think?

**Comment by nacho** [comment]
You convinced me :)

**Comment by danyeaw** [comment]
Thanks @nacho!

**Pull request merged**
