### PR TITLE
librsvg: add patch to link against bcrypt

### PR DESCRIPTION
**Pull request by mhertz**

### CODE REVIEW

**Comment by danyeaw** [comment]
Thanks @mhertz and @nacho!

**Comment by nacho** [comment]
thanks for the patch!

**Comment by pbor** [comment]
Can you also file it upstream in the librsvg repo?

**Comment by danyeaw** [comment]
@pbor Good idea. @mhertz Is that something you would be willing to lead?

Maybe we could try to get both patches upstream. :+1:

**Comment by mhertz** [comment]
Thanks guys and sure :)

Bcrypt: https://gitlab.gnome.org/GNOME/librsvg/-/merge_requests/645

Cairo: https://gitlab.gnome.org/GNOME/librsvg/-/merge_requests/646

**Comment by danyeaw** [comment]
Thanks @mhertz, that's awesome!

**Pull request merged**
