### PR TITLE
openssl: update to version 3.2.1

### PR DESCRIPTION
**Pull request by nacho**

### CODE REVIEW

**Review by pbor — COMMENTED** [review]
I will leave review to nacho/alessandro for the openssl stuff

**Comment by nacho** [comment]
It seems that I can not approve it :( Thanks for fixing the patch! Any idea if this is something we should report upstream? @pbor can you merge it?

**Review by pbor — APPROVED** [review]
I am approving as suggested by Nacho.

It is unclear to me how these updates impact the FIPS part

**Comment by danyeaw** [comment]
I took the patch from upstream, the link to the commit is in my commit message.

**Comment by nacho** [comment]
There is no other FIPs release so I think we are good to merge this now.

**Comment by nacho** [comment]
One note about this, we tested glib-networking with openssl 3.2 and there was some regression which we do not know if it will affect also Windows. Just a note that we might need to revert this if it also happens for windows

**Pull request merged**
