### PR TITLE
Weekly dependency update

### PR DESCRIPTION
**Pull request by danyeaw**

### CODE REVIEW

**Comment by nacho** [comment]
@AlessandroBono I think we reverted the update of nghttp for some reason?

**Comment by nacho** [comment]
https://github.com/wingtk/gvsbuild/commit/40a92e4968313139556ac576130d948bfd93bbd0

**Comment by AlessandroBono** [comment]
The nghttp2 update got reverted because if you try to compile it you get:
```
   ninja: error: build.ninja:661: multiple rules generate lib/nghttp2.lib
```

**Comment by danyeaw** [comment]
Good catch!

**Review by nacho — APPROVED** [review]

**Pull request merged**
