### PR TITLE
Update gstreamer and plugins to 1.20.2

### PR DESCRIPTION
**Pull request by danyeaw**

### CODE REVIEW

**Comment by danyeaw** [comment]
`gst-plugins-base` is failing with:

```
Couldn't find include 'Gst-1.0.gir' (search path: '['C:/gtk-build/gtk/x64/release/bin/../share/gir-1.0', 'C:\\gtk-build\\gtk\\x64\\release\\share', 'gir-1.0', 'C:\\gtk-build\\gtk\\x64\\release\\share\\gir-1.0']')
```

**Comment by nacho** [comment]
> `gst-plugins-base` is failing with:
> 
> ```
> Couldn't find include 'Gst-1.0.gir' (search path: '['C:/gtk-build/gtk/x64/release/bin/../share/gir-1.0', 'C:\\gtk-build\\gtk\\x64\\release\\share', 'gir-1.0', 'C:\\gtk-build\\gtk\\x64\\release\\share\\gir-1.0']')
> ```

has this been fixed?

**Comment by danyeaw** [comment]
Nope, it looks like gstreamer is broken which makes me wonder if anyone is actually using it? :thinking:

**Comment by nacho** [comment]
We are using gstreamer, although I admit that we do not use gobject introspection and maybe that is the reason we did not see the failure on our side...

**Comment by danyeaw** [comment]
Ok, that's good that it is being used. I'll see if I can take a look in to the gobject-introspection issue at some point.

**Comment by nacho** [comment]
I think we can merge this for now, or is the g-i a regression?

**Comment by danyeaw** [comment]
I don't think it is a regression, I'll open an issue.

**Pull request merged**
