### PR TITLE
Add fftw3 3.3.10

### PR DESCRIPTION
**Pull request by alex-tee**
need this for Zrythm

### CODE REVIEW

**Comment by danyeaw** [comment]
Hi @alex-tee Zrythm looks like a cool project! Would you be willing to help maintain these libraries including keeping them up to date if we merge this?

**Comment by alex-tee** [comment]
Hi @danyeaw I do plan to maintain all the libraries I submit if I end up using gvsbuild. I'm still going through my dependencies so can't say for sure yet though.

**Comment by alex-tee** [comment]
Sorry some of my dependencies do not work with msvc (they use pthreads and VLAs for example) so I won't be able to maintain these. I packaged a couple more packages so please let me know if you want them or if I should close the PRs.

These are the packages I have so far: fftw, fluidsynth, libsamplerate, liblo, zstd

**Comment by pbor** [comment]
If we have no active users and since they seem very niche, I would rather not take them for the time being.

I think we should take zstd though, since that may be more generally useful

**Pull request closed without merging**
