### PR TITLE
Make OpenSSL with FIPS a build option

### LINKED ISSUE #1214: OpenSSL is Shown as Outdated
In https://github.com/wingtk/gvsbuild/pull/1162 we added a FIPS provider for OpenSSL. However, this created a couple of issues:

1. `gvsbuild outdated` always shows that OpenSSL is outdated, since the module called openssl is now the old version we are getting the FIPS provider from. We will also very likely miss OpenSSL versions being released like this.
2. OpenSSL moves LTS versions after they aren't the latest version. So the FIPS provider was at https://www.openssl.org/source/openssl-3.0.8.tar.gz, and then was moved to https://www.openssl.org/source/old/3.0/openssl-3.0.8.tar.gz after a newer 3.0.x version was released. This broke the build.

Any thoughts on how we can resolve these?

### PR DESCRIPTION
**Pull request by danyeaw**
This PR fixes #1214 by making building with the FIPS cryptographic certification optional.

If users want to enable it, they can run `gvsbuild build --enable-fips openssl`. Each project making use of OpenSSL adds either openssl or openssl-fips as the dependency based on that option.

### CODE REVIEW

**Comment by nacho** [comment]
@AlessandroBono please have a look at this

**Review by AlessandroBono — CHANGES_REQUESTED** [review]

**Comment by danyeaw** [comment]
I think this is ready to go now 👍.

**Comment by danyeaw** [comment]
@nacho, @AlessandroBono, and @pbor, could someone please do a new review of this when you get a chance?

**Comment by AlessandroBono** [comment]
LGTM

**Review by pbor — APPROVED** [review]

**Pull request merged**
