### PR TITLE
Add Support for GTK4

### LINKED ISSUE #490: Can I use this project to build GTK 4?
Hi, is it possible to use gvsbuild for GTK 4 instead of 3?

### PR DESCRIPTION
**Pull request by danyeaw**
This PR adds support for GTK4. In order to do that I also upgraded some other tools and projects including meson, pango, librsvg, and graphene.

In order to build it, I ran:
```
 python .\build.py build -p=x64 --vs-ver=16 --msys-dir=C:\tools\msys64 --enable-gi --py-wheel gobject-introspection gtk4 pycairo pygobject adwaita-icon-theme hicolor-icon-theme
```
The build was successful, and I tested a hello world app:

```
import gi
gi.require_version('Gtk', '4.0')
from gi.repository import Gtk

def on_activate(app):
    win = Gtk.ApplicationWindow(application=app, title="Hello GTK4")
    win.present()

app = Gtk.Application()
app.connect('activate', on_activate)

app.run(None)
```

image

This PR closes #490.

### CODE REVIEW

**Comment by pbor** [comment]
Nice! I think we should also update the README to cover this

**Comment by pbor** [comment]
By the way I think we should drop gtk 3.22 and 3.20.. there is really no reason why at this point anyone should be using those. I think we should have three projects: Gtk2, Gtk3, Gtk4

**Comment by pbor** [comment]
Anyway, those things are not blockers to merge, they can be done after.

However before merging, the CI should pass

**Comment by nacho** [comment]
nice!

**Comment by danyeaw** [comment]
@nacho Could we also please update the gvsbuild project description from GTK+ 3 stack for Windows to GTK stack for Windows?

**Comment by nacho** [comment]
> @nacho Could we also please update the gvsbuild project description from GTK+ 3 stack for Windows to GTK stack for Windows?

Done

**Comment by nacho** [comment]
This looks ready to me, is there anything else missing?

**Comment by danyeaw** [comment]
@nacho I think it is ready, thanks!

**Comment by nacho** [comment]
great job! thanks

**Pull request merged**
