### PR TITLE
Enable Automated Release to PyPI

### PR DESCRIPTION
**Pull request by danyeaw**
gvsbuild is now pip installable and is a project at https://pypi.org/project/gvsbuild.

This PR adds the following:

- Enables dependabot to keep dependencies up to date
- Enable the release-drafter GitHub Action which will start drafting the next release as each PR is merged
- Add build steps to automatically upload to PyPI
- Make pipx the default way to install gvsbuild instead of cloning the repo

I was planning on about monthly releases, with micro version updates for bug fixes if needed. @nacho or @lazka, could you please give me access to add GitHub Action secrets to the repo?

### CODE REVIEW

**Comment by lazka** [comment]
> I was planning on about monthly releases, with micro version updates for bug fixes if needed. @nacho or @lazka, could you please give me access to add GitHub Action secrets to the repo?

I don't think I can decide that, but I also have nothing against it if that helps.

**Review by pbor — APPROVED** [review]
Sure, I am ok with this... what do I need to do to grant you permissions?

**Comment by pbor** [comment]
One question I have (and forgive my pip ignoarance): how does one pin to a specific version?

Eg, if I want to be able to rebuild the exact same snapshot of my dependencies rather than the latest and greatest, I would go about it?

**Comment by danyeaw** [comment]
> Sure, I am ok with this... what do I need to do to grant you permissions?

https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository

Says that I need admin access. Alternatively I can give someone access to the PyPI project and they can create a secret.

**Comment by danyeaw** [comment]
> One question I have (and forgive my pip ignoarance): how does one pin to a specific version?

`pip install gvsbuild==2022.1.0`

**Comment by pbor** [comment]
> Says that I need admin access.

Should be ok now

**Comment by danyeaw** [comment]
@pbor Thanks! That worked great, and I added the PyPI token as a secret.

**Pull request merged**
