### PR TITLE
Test/gi update 1

### PR DESCRIPTION
**Pull request by guruDanny67**
Update to let gobject-introspection make the gir/typelib for gdk-pixbuf: with the last update a couple of files are missing.

### CODE REVIEW

**Comment by nacho** [comment]
Feel free to push but is it something that we should fix upstream in gdk pixbuf?

**Comment by guruDanny67** [comment]
Yes, it's a hack to have the gi built.
In the long run we shoud make gi depends only on glib and make only the gir for the low level libs, the one handled directly by the gi sources.
The other gir/typelibs (atk, gtk3, emeus, ...) should be handled by the single project (with meson should be really easy, probably we have only to drop some option from our command line ...).
To prepare for this we can split the gi build in two (or more) projects, the first makes only the gobject-introspection and the other builds the variuos gir (we can have gtk3-gir, gtk-gir, atk-gir, ...).
With the groups we can handle this easily and we are ready where the single project (say gdk-pixbuf) create the gir.
Maybe we should have an option --build-gir=yes|no to enable this, or simply look for the giscanner program or let the meson script decide.
It's really something we shoud fix, sooner or later.

**Comment by dave-khuon** [comment]
Great news.  I will check it out sometime today.  Thanks for letting me
know.

**Comment by dave-khuon** [comment]
Do we have it as a package I can add to my Visual Studio project environment (yet?).  Thanks.

**Pull request merged**
