### PR TITLE
Fix python's lib folder search on virtualenv

### PR DESCRIPTION
**Pull request by DjLegolas**
the current way to find it looks for a file that was changed after a refactor `virtualenv` had

### CODE REVIEW

**Comment by danyeaw** [comment]
Hi @DjLegolas, thanks so much for another contribution! Since there is no issue linked to this and your description is pretty brief, could you please explain more about what issue this is fixing and under which condition? It will help me with context while reviewing it. Thanks!

**Comment by DjLegolas** [comment]
@danyeaw yeah sure, I just forgot to add the relevant details.

Basically, the issue happens when compiling a `debug` build, including `python` support and using a `venv`.
For `gvsbuild` to build `gobject-introspection` with `debug` support, it searches for the `libs` folder that should contain python's debug lib (`python3x_d.lib` file).
The issue it that the way of getting the base path of the interpreter was changed. Currently, the path to the base is located inside a file `pyenv.cfg` in the root of the `venv` folder. Therefor, I added the support for it.
Nevertheless, as I'm not sure that we need to still support the older way, I decided to kept it, just in case.

This issue was partially reported in https://github.com/wingtk/gvsbuild/issues/1451, but it also reports another issue with the build. I suspect it's something related to the upstream, but wasn't able to figure out yet.

**Review by danyeaw — COMMENTED** [review]
Hi @DjLegolas, got it, thanks for the explanation! I don't know of any recent changes to virtualenvs since the venv module was added in Python 3.3 with PEP 405. Looking for the pyenv.cfg file makes sense, I vote that you remove the legacy method.

**Comment by DjLegolas** [comment]
@danyeaw the change is not recent, and probably not related to the builtin `venv` module from `python`.
In the original [`virtualenv`](https://github.com/pypa/virtualenv) module, on versions before `20.0.0`, the `orig-prefix.txt` was in use.
Therefor, when the `python_find_libs_dir` function was added back in 4583c94e (2017), the `virtualenv` module had only the `orig-prefix.txt`, but it seem it was never tested on the builtin `venv` module.

> Looking for the pyenv.cfg file makes sense, I vote that you remove the legacy method.

I have removed the legacy part - will now only support `pyvenv.cfg`.

**Review by danyeaw — APPROVED** [review]
Thanks @DjLegolas, this is a great fix!

**Pull request merged**
