### PR TITLE
Normalize Line Endings in Project

### PR DESCRIPTION
**Pull request by danyeaw**
This PR puts in place best practices for dealing with line endings:
Please see [GitHub: Dealing with Line Endings](https://help.github.com/articles/dealing-with-line-endings/)

All Windows users should have:
`git config --global core.autocrlf true` set, so that text files aren't put in a git repository with CRLF endings. Since the majority of the files have been commited with CRLF line endings, this prevents anyone to contribute to this project who has their Windows git configured correctly, or who is on OSX or Linux.

Since it is hard to enforce Windows users to setup git correctly, this PR creates a .gitattributes file that normalizes them for the project. I then renormalized all the files in the repository to fix all of the current line endings.

### CODE REVIEW

**Comment by danyeaw** [comment]
Is this something that the team is interested in merging? Is so, I can resolve the conflicts with master.

**Comment by danyeaw** [comment]
@nacho and @guruDanny67 is this something you are interested in fixing, or should I close the PR? :heart:

**Comment by nacho** [comment]
So what I don't like from these kind of patches is that you lose blaming making more difficult to understand why the line changed. In any case thanks a lot for the patch.

**Comment by cas--** [comment]
This obviously didn't work as [32dc00d8a15ae758459cc5baeeea78d086ef669c] just reset all the line endings to `CRLF` and borked the commit history for projects.py!

**Pull request closed without merging**
