### PR TITLE
Weekly Updates

### PR DESCRIPTION
**Pull request by danyeaw**
- dcv-color-primities to version 0.5.2
- gtk3 to version 3.24.37
- harfbuzz to version 7.1.0
- nghttp2 to version 1.52.0

### CODE REVIEW

**Comment by pbor** [comment]
I am a bit concerned about ffmpeg 6... It is not 100% clear to me if it is a breaking change for applications using gvsbuild

**Comment by danyeaw** [comment]
Hi @pbor, I could drop the commit if needed. I am not sure if other apps (besides FreeRDP) are using ffmpeg as a dependency. I could try building FreeRDP with it. If other apps are depending on ffmpeg, they could pin their gvsbuild version, but I think we should always be trying to ship the latest stable versions if possible.

**Comment by pbor** [comment]
In general I agree that we should ship the newest stable version, but for large things like gtk, we keep gtk3 and gtk4 as not all apps immediately switch. I am not super familiar on what kind of API/ABI breaks happen with major versions in ffmpeg.

At work we depend on ffmpeg we will probably wait for a couple of patch releases before switching.
If it is not too much work, I would keep that on hold for a little bit (eg until a .1 release).

Feel free to merge the rest of the updates.

**Comment by danyeaw** [comment]
It looks like ffmpeg needs to be repatched. I dropped it from this PR and I'll make a separate on with an update soon.

**Comment by nacho** [comment]
Thanks for the patches

**Pull request merged**
