### PR TITLE
Build both GTK3 and GTK4 with CI

### PR DESCRIPTION
**Pull request by danyeaw**
This PR updates the CI to build both GTK3 and GTK4.

### CODE REVIEW

**Comment by pbor** [comment]
We had to revert this one since CI started timing out... I however agree that we need to add gtk4, we just need to understand what is going on

**Comment by nacho** [comment]
Sounds good to me

**Comment by danyeaw** [comment]
@pbor Do you know how we would do that with GitHub Actions? Store an intermediate build in the cache?

**Comment by pbor** [comment]
yeah... we would have to cache it, no idea if it is worth it

**Comment by pbor** [comment]
unless using a workflow with multiple stages allows to carry over the output

**Pull request merged**
