### PR TITLE
Add GTK Installers for Windows

### PR DESCRIPTION
**Pull request by danyeaw**
This PR adds InnoSetup setup installers for most of the core gvsbuild projects.

It would be a step towards closing #145, to provide pre-built binaries for Windows.

Following this PR:
1. Set up CI to automatically release a new version of a library when we tag a new version.
2. Add the packages to Chocolatey (including dependencies between the installers).
3. Release wheels to Windows in PyPI

### CODE REVIEW

**Comment by nacho** [comment]
Do we really want to provide an installer for the binaries? dunno, Also I wonder if we should use Wix instead of Innosetup

**Comment by danyeaw** [comment]
Hey @nacho, I thought I would throw it out there to see if it is something we want to take on as part of this repository. I think giving Windows users an easy way to install GTK is very important. It would also help with other projects making use of gvsbuild, I would rather run `choco install GTK` in GitHub Actions than rebuild from source and store it in cache.

I used InnoSetup because it is simple. It looks like Wix would be quite a bit more effort, and unless we are planning on needing MSI/X (say for Microsoft store) then it might not be worth it. This is the kind of feedback I am looking for though, would we rather have a MSI rather than an simple exe installer?

**Comment by TingPing** [comment]
Late reply but having used Inno for years, I think its a totally fine solution.

**Comment by TingPing** [comment]
If it were me I would have one larger installer with optional components. I don't really see the value in a dozen separate installers.

**Pull request closed without merging**
