### PR TITLE
Remove Quiche

### PR DESCRIPTION
**Pull request by danyeaw**

### CODE REVIEW

**Comment by nacho** [comment]
Quiche is tricky because you need the right version of boringssl to be aligned properly. I'll ask my colleague to take a look

**Comment by pbor** [comment]
Shall we even keep it? I think we added it when we were looking at the C api, but now we consume it as a rust dep... I am not sure any other user of gvsbuild care about it

**Comment by nacho** [comment]
Let's see what Biagio says and if something we can just remove it

**Comment by BiagioFesta** [comment]
We consume `quiche` as rust dependency, so we are not impacted on this change.

**Comment by danyeaw** [comment]
Instead of updating quiche, are there any objections if I just remove quiche and boringssl?

**Comment by BiagioFesta** [comment]
I think we can safely remove quiche build. 

However, we need to keep boringssl as dependency. I am planning to update boringssl soon.

**Comment by nacho** [comment]
Thanks

**Pull request merged**
