### PR TITLE
libxml2: update to version 2.10.0

### PR DESCRIPTION
**Pull request by nacho**

### CODE REVIEW

**Comment by nacho** [comment]
We need to understand why this does not build :(

**Comment by nacho** [comment]
```
include\libxml\meson.build:1: WARNING: The variable(s) 'WITH_XPTR_LOCS' in the input file 'include/libxml\xmlversion.h.in' are not present in the given configuration data.

include\libxml\meson.build:9:0: ERROR: File DOCBparser.h does not exist.

A full log can be found at C:\gtk-build\build\x64\release\libxml2\_gvsbuild-meson\meson-logs\meson-log.txt
Traceback (most recent call last):
  File "D:\a\gvsbuild\gvsbuild\gvsbuild\utils\builder.py", line 531, in build
    if self.__build_one(p):
  File "D:\a\gvsbuild\gvsbuild\gvsbuild\utils\builder.py", line 667, in __build_one
    skip_deps = proj.build()
  File "D:\a\gvsbuild\gvsbuild\gvsbuild\projects\libxml2.py", line 35, in build
    Meson.build(self)
  File "D:\a\gvsbuild\gvsbuild\gvsbuild\utils\base_builders.py", line 47, in build
    self._setup_meson_and_ninja(ninja_build, meson_params, add_path)
  File "D:\a\gvsbuild\gvsbuild\gvsbuild\utils\base_builders.py", line 78, in _setup_meson_and_ninja
    self.exec_vs(cmd, add_path=add_path)
  File "D:\a\gvsbuild\gvsbuild\gvsbuild\utils\base_project.py", line 113, in exec_vs
    self.builder.exec_vs(
  File "D:\a\gvsbuild\gvsbuild\gvsbuild\utils\builder.py", line 943, in exec_vs
    self.__execute(
  File "D:\a\gvsbuild\gvsbuild\gvsbuild\utils\builder.py", line 1045, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\hostedtoolcache\windows\Python\3.10.6\x64\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\gtk-build\tools\python.3.10.5\tools\python.exe C:\gtk-build\tools\meson-0.63.0\meson.py C:\gtk-build\build\x64\release\libxml2 C:\gtk-build\build\x64\release\libxml2\_gvsbuild-meson --prefix C:\gtk-build\gtk\x64\release --buildtype debugoptimized' returned non-zero exit status 1.
Error: libxml2 build failed
```

**Comment by nacho** [comment]
https://gitlab.gnome.org/GNOME/libxml2/-/issues/394

**Comment by nacho** [comment]
Actually it seems that we have now a meson project that we are maintaining, it will need some fixes

**Comment by TingPing** [comment]
I updated the list of installed headers and bumped the version there.

However I don't have time to test it any further so I just pushed it here for you.

As for upstream there is only the request: https://gitlab.gnome.org/GNOME/libxml2/-/issues/328

I believe my files were based on the wrapdb of libxml2 which is also outdated: https://github.com/mesonbuild/wrapdb/tree/master/subprojects/packagefiles/libxml2

**Comment by TingPing** [comment]
> WARNING: The variable(s) 'WITH_XPTR_LOCS' in the input file 'include/libxml\xmlversion.h.in' are not present in the given configuration data.

Need to define this too.

**Comment by saste** [comment]
> We need to understand why this does not build :(

This diff fixes the build here:
```
--- a/gvsbuild/patches/libxml2/meson.build
+++ b/gvsbuild/patches/libxml2/meson.build
@@ -212,6 +212,7 @@ withcdata.set10('WITH_CATALOG', true)
 withcdata.set10('WITH_DOCB', true)
 withcdata.set10('WITH_XPATH', true)
 withcdata.set10('WITH_XPTR', true)
+withcdata.set10('WITH_XPTR_LOCS', true)
 withcdata.set10('WITH_XINCLUDE', true)
 withcdata.set10('WITH_ICONV', iconv_lib.found())
 withcdata.set10('WITH_ICU', false)
withcdata.set10('WITH_XPTR_LOCS', true)
```

In the long term, I'd prefer to drop the meson port and go back to the native build to avoid to manually update the meson files every time.

**Comment by TingPing** [comment]
It looks like upstream does support `nmake`. I think it will only be worse than `meson` but its worth a shot.

**Pull request merged**
