### PR TITLE
Update GLib to version 2.82.0

### PR DESCRIPTION
**Pull request by DjLegolas**
Now that `glib` 2.82.0 is released, we can upgrade to it.

### CODE REVIEW

**Comment by pbor** [comment]
See https://github.com/wingtk/gvsbuild/issues/1419 . I think we need this when we update glib.

Also, glib-networking usually has to be updated in lockstep with glib

**Comment by DjLegolas** [comment]
> See #1419 . I think we need this when we update glib.

I'll into it and add it in a separate commit

> Also, glib-networking usually has to be updated in lockstep with glib

`glib-networking` is already at it's latest release (2.80.0)

**Review by danyeaw — CHANGES_REQUESTED** [review]
Please fix the lint error with `pre-commit install` and then `pre-commit run --all-files`. Thanks!

**Comment by DjLegolas** [comment]
Fixed :)

**Review by danyeaw — APPROVED** [review]

**Comment by danyeaw** [comment]
Thanks @DjLegolas!

**Pull request merged**
