### PR TITLE
Added a group class to combine easily differents projects

### PR DESCRIPTION
**Pull request by guruDanny67**
So we can have a single project that downloads and unpack all the tools, one for building all the gtk3 stuff, ..

### CODE REVIEW

**Comment by nacho** [comment]
Dunno I am fine with it but better to push once it is used no?

**Comment by nacho** [comment]
Also fix the copyright and put ur name

**Comment by guruDanny67** [comment]
I've got, ready, two modules for using this (to build all the tools and all the Gtk3 stuff), I keep it separated just to have two commits and be clear on the the two things.

**Comment by nacho** [comment]
I can see a merge commit... can you try to get rid of it?

**Comment by guruDanny67** [comment]
I'm making a single commit with the group class and the use of it. If you're ok I will merge it to master.

Tnahks

**Comment by nacho** [comment]
Looks good to me. Go ahead and push it

**Pull request merged**
