### PR TITLE
Extend list command

### PR DESCRIPTION
**Pull request by saste**
This is needed to simplify processing the output generated by the list command.

### CODE REVIEW

**Comment by pbor** [comment]
I am ok with this idea... can you show an output?

In terms of merging, this probably conflicts with https://github.com/wingtk/gvsbuild/pull/659 so we will need to understand what should go first

**Comment by saste** [comment]
> I am ok with this idea... can you show an output?

```
PS> py .\build.py list glib
Running build.py directly is now deprecated, please run `pip install .`
Available projects with type project:
        glib                      2.72.4
PS> py .\build.py list glib --deps
Running build.py directly is now deprecated, please run `pip install .`
Available projects with type project:
        glib                      2.72.4
        zlib                      1.2.13
        win-iconv                 0.0.8
        gettext                   0.21
        libffi                    git/meson-3.2.9999.4
        pkg-config                1.8.0
Available projects with type tool:
        cmake                     3.24.2
        meson                     0.63.2
        python
        ninja                     1.11.0
        nuget                     6.3.0
PS> py .\build.py list glib --deps --type project
Running build.py directly is now deprecated, please run `pip install .`
Available projects with type project:
        gettext                   0.21
        pkg-config                1.8.0
        zlib                      1.2.13
        glib                      2.72.4
        win-iconv                 0.0.8
        libffi                    git/meson-3.2.9999.4
PS> py .\build.py list glib --deps --json
Running build.py directly is now deprecated, please run `pip install .`
{
    "cmake": {
        "dependencies": [],
        "project": "3.24.2",
        "type": "tool"
    },
    "gettext": {
        "dependencies": [
            "python",
            "win-iconv"
        ],
        "project": "0.21",
        "type": "project"
    },
    "glib": {
        "dependencies": [
            "ninja",
            "meson",
            "pkg-config",
            "gettext",
            "libffi",
            "zlib"
        ],
        "project": "2.72.4",
        "type": "project"
    },
    "libffi": {
        "dependencies": [
            "python",
            "ninja",
            "meson"
        ],
        "project": "git/meson-3.2.9999.4",
        "type": "project"
    },
    "meson": {
        "dependencies": [
            "python"
        ],
        "project": "0.63.2",
        "type": "tool"
    },
    "ninja": {
        "dependencies": [],
        "project": "1.11.0",
        "type": "tool"
    },
    "nuget": {
        "dependencies": [],
        "project": "6.3.0",
        "type": "tool"
    },
    "pkg-config": {
        "dependencies": [
            "ninja",
            "meson"
        ],
        "project": "1.8.0",
        "type": "project"
    },
    "python": {
        "dependencies": [
            "nuget"
        ],
        "type": "tool"
    },
    "win-iconv": {
        "dependencies": [
            "cmake",
            "ninja"
        ],
        "project": "0.0.8",
        "type": "project"
    },
    "zlib": {
        "dependencies": [],
        "project": "1.2.13",
        "type": "project"
    }
}
```

Note, probably we want to merge the outdated feature with list through options.

> In terms of merging, this probably conflicts with #659 so we will need to understand what should go first

I'm fine with either, rebasing should be pretty easy (but probably it's also true the other way).

**Comment by saste** [comment]
@danyeaw can you have a look at it? Is it ok to merge before your https://github.com/wingtk/gvsbuild/pull/659 branch?

**Comment by saste** [comment]
> My preference would to merge #659 first, since these changes would be much easier to rebase / apply once we have that in.
> 
> Can you explain what this is used for, what are you using these outputs for?

It's in the commit log, I have a bunch of projects which I build with gvsbuild and I need to process the generated versions. For this I need to select the subset of built packages, and then I need to parse the `list` output. I could parse the current custom format, but it's much easier and extensible to adopt JSON to simplify parsing.

**Pull request merged**
