### PR TITLE
Fix vs2022build lz4

### PR DESCRIPTION
**Pull request by iAnyKey**
fixes https://github.com/wingtk/gvsbuild/issues/520

`python ./build.py build --build-dir=$pwd\\..\\gtk -p=x64 --vs-ver=17 --msys-dir="$pwd\\..\\msys64" lz4 && cd ..`
results into:
```
Cleaning up the build environment
Checking msys tool
Checking Msvc tool
Downloading packages
C:\flan2\build\gvsbuild\\..\\gtk\src\nuget-5.4.0.exe - Download finished
C:\flan2\build\gvsbuild\\..\\gtk\src\lz4-1.9.3.tar.gz - Download finished
Building project nuget (5.4.0)
Feeds used:
  C:\Users\_\.nuget\packages\
  https://api.nuget.org/v3/index.json
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\



Attempting to gather dependency information for package 'python.3.10.4' with respect to project 'C:\flan2\build\gtk\tools', targeting 'Any,Version=v0.0'
Gathering dependency information took 192,28 ms
Attempting to resolve dependencies for package 'python.3.10.4' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'python.3.10.4'
Resolved actions to install package 'python.3.10.4'
Retrieving package 'python 3.10.4' from 'C:\Users\_\.nuget\packages\'.
Adding package 'python.3.10.4' to folder 'C:\flan2\build\gtk\tools'
Added package 'python.3.10.4' to folder 'C:\flan2\build\gtk\tools'
Successfully installed 'python 3.10.4' to C:\flan2\build\gtk\tools
Executing nuget actions took 4,42 sec
Requirement already satisfied: pip in c:\flan2\build\gtk\tools\python.3.10.4\tools\lib\site-packages (22.0.4)
Requirement already satisfied: setuptools in c:\flan2\build\gtk\tools\python.3.10.4\tools\lib\site-packages (58.1.0)
Collecting setuptools
  Using cached setuptools-61.2.0-py3-none-any.whl (1.1 MB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 58.1.0
    Uninstalling setuptools-58.1.0:
      Successfully uninstalled setuptools-58.1.0
Successfully installed setuptools-61.2.0
Collecting wheel
  Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel
Successfully installed wheel-0.37.1
Collecting build
  Using cached build-0.7.0-py3-none-any.whl (16 kB)
Collecting packaging>=19.0
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting tomli>=1.0.0
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting pep517>=0.9.1
  Using cached pep517-0.12.0-py2.py3-none-any.whl (19 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.7-py3-none-any.whl (98 kB)
Installing collected packages: tomli, pyparsing, colorama, pep517, packaging, build
Successfully installed build-0.7.0 colorama-0.4.4 packaging-21.3 pep517-0.12.0 pyparsing-3.0.7 tomli-2.0.1
Building project python ()
(tar) Exporting lz4
Building project lz4 (1.9.3)
Checking for 'C:\flan2\build\gvsbuild\\..\\gtk\build\x64\release\lz4\visual\vs17\lz4.sln'
Checking for 'C:\flan2\build\gvsbuild\\..\\gtk\build\x64\release\lz4\visual\vs2022\lz4.sln'
  lz4.c
  lz4frame.c
  lz4hc.c
  xxhash.c
  datagen.c
  bench.c
  lz4cli.c
  lz4io.c
  Code Analysis für C/C++ wird ausgeführt...
  Code wird generiert.
  Previous IPDB not found, fall back to full compilation.
  All 287 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Codegenerierung ist abgeschlossen.
  lz4.vcxproj -> C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\bin\x64_Release\lz4.exe
C:\flan2\build\gtk\build\x64\release\lz4\lib\lz4.c(489): warning C6385: Lesen ungültiger Daten von "v
":  die lesbare Größe beträgt "_Old_4`2" Byte, es können jedoch "4" Byte gelesen werden. [C:\flan2\bu
ild\gtk\build\x64\release\lz4\visual\vs2022\lz4\lz4.vcxproj]
C:\flan2\build\gtk\build\x64\release\lz4\programs\bench.c(327): warning C26451: Arithmetischer Überla
uf: Wenn Sie den Operator "+" für einen 4-Bytewert verwenden und das Ergebnis in einen 8-Bytewert umw
andeln, wandeln Sie den Wert in den breiteren Typ um, bevor Sie den Operator "+" verwenden, um einen
Überlauf zu vermeiden (io.2). [C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\lz4\lz4.vcxproj
]
C:\flan2\build\gtk\build\x64\release\lz4\programs\lz4io.c(432): warning C6385: Lesen ungültiger Daten
 von "out_buff":  die lesbare Größe beträgt "(size_t)outBuffSize+4" Byte, es können jedoch "4" Byte g
elesen werden. [C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\lz4\lz4.vcxproj]
C:\flan2\build\gtk\build\x64\release\lz4\programs\lz4io.c(455): warning C26451: Arithmetischer Überla
uf: Wenn Sie den Operator "+" für einen 4-Bytewert verwenden und das Ergebnis in einen 8-Bytewert umw
andeln, wandeln Sie den Wert in den breiteren Typ um, bevor Sie den Operator "+" verwenden, um einen
Überlauf zu vermeiden (io.2). [C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\lz4\lz4.vcxproj
]
C:\flan2\build\gtk\build\x64\release\lz4\programs\lz4io.c(467): warning C26451: Arithmetischer Überla
uf: Wenn Sie den Operator "-" für einen 4-Bytewert verwenden und das Ergebnis in einen 8-Bytewert umw
andeln, wandeln Sie den Wert in den breiteren Typ um, bevor Sie den Operator "-" verwenden, um einen
Überlauf zu vermeiden (io.2). [C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\lz4\lz4.vcxproj
]
C:\flan2\build\gtk\build\x64\release\lz4\programs\lz4io.c(589): warning C6386: Pufferüberlauf beim Sc
hreiben nach "dictBuf":  die schreibbare Größe beträgt "dictLen?dictLen:1" Byte, es können jedoch "1"
 Byte geschrieben werden. [C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\lz4\lz4.vcxproj]
C:\flan2\build\gtk\build\x64\release\lz4\programs\lz4io.c(787): warning C26451: Arithmetischer Überla
uf: Wenn Sie den Operator "-" für einen 4-Bytewert verwenden und das Ergebnis in einen 8-Bytewert umw
andeln, wandeln Sie den Wert in den breiteren Typ um, bevor Sie den Operator "-" verwenden, um einen
Überlauf zu vermeiden (io.2). [C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\lz4\lz4.vcxproj
]
C:\flan2\build\gtk\build\x64\release\lz4\programs\lz4io.c(962): warning C6386: Pufferüberlauf beim Sc
hreiben nach "in_buff":  die schreibbare Größe beträgt "LZ4_compressBound((8*((1<<20))))" Byte, es kö
nnen jedoch "4" Byte geschrieben werden. [C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\lz4\
lz4.vcxproj]
C:\flan2\build\gtk\build\x64\release\lz4\programs\lz4io.c(1300): warning C26451: Arithmetischer Überl
auf: Wenn Sie den Operator "-" für einen 4-Bytewert verwenden und das Ergebnis in einen 8-Bytewert um
wandeln, wandeln Sie den Wert in den breiteren Typ um, bevor Sie den Operator "-" verwenden, um einen
 Überlauf zu vermeiden (io.2). [C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\lz4\lz4.vcxpro
j]
C:\flan2\build\gtk\build\x64\release\lz4\programs\lz4io.c(1454): warning C26451: Arithmetischer Überl
auf: Wenn Sie den Operator "+" für einen 4-Bytewert verwenden und das Ergebnis in einen 8-Bytewert um
wandeln, wandeln Sie den Wert in den breiteren Typ um, bevor Sie den Operator "+" verwenden, um einen
 Überlauf zu vermeiden (io.2). [C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\lz4\lz4.vcxpro
j]
  lz4.c
  lz4frame.c
  lz4hc.c
  xxhash.c
  Code Analysis für C/C++ wird ausgeführt...
     Bibliothek "C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\bin\x64_Release\liblz4.lib" u
  nd Objekt "C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\bin\x64_Release\liblz4.exp" werde
  n erstellt.
  Code wird generiert.
  Previous IPDB not found, fall back to full compilation.
  All 204 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Codegenerierung ist abgeschlossen.
  liblz4-dll.vcxproj -> C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\bin\x64_Release\liblz4
  .dll
C:\flan2\build\gtk\build\x64\release\lz4\lib\lz4.c(489): warning C6385: Lesen ungültiger Daten von "v
":  die lesbare Größe beträgt "_Old_4`2" Byte, es können jedoch "4" Byte gelesen werden. [C:\flan2\bu
ild\gtk\build\x64\release\lz4\visual\vs2022\liblz4-dll\liblz4-dll.vcxproj]
  lz4.c
  lz4frame.c
  lz4hc.c
  xxhash.c
  Code Analysis für C/C++ wird ausgeführt...
  liblz4.vcxproj -> C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\bin\x64_Release\liblz4_sta
  tic.lib
C:\flan2\build\gtk\build\x64\release\lz4\lib\lz4.c(489): warning C6385: Lesen ungültiger Daten von "v
":  die lesbare Größe beträgt "_Old_4`2" Byte, es können jedoch "4" Byte gelesen werden. [C:\flan2\bu
ild\gtk\build\x64\release\lz4\visual\vs2022\liblz4\liblz4.vcxproj]
  lz4.c
  lz4hc.c
  xxhash.c
  fuzzer.c
  Code Analysis für C/C++ wird ausgeführt...
  Code wird generiert.
  Previous IPDB not found, fall back to full compilation.
  All 159 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Codegenerierung ist abgeschlossen.
  fuzzer.vcxproj -> C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\bin\x64_Release\fuzzer.exe
C:\flan2\build\gtk\build\x64\release\lz4\lib\lz4.c(489): warning C6385: Lesen ungültiger Daten von "v
":  die lesbare Größe beträgt "_Old_4`2" Byte, es können jedoch "4" Byte gelesen werden. [C:\flan2\bu
ild\gtk\build\x64\release\lz4\visual\vs2022\fuzzer\fuzzer.vcxproj]
C:\flan2\build\gtk\build\x64\release\lz4\tests\fuzzer.c(497): warning C6385: Lesen ungültiger Daten v
on "compressedBuffer":  die lesbare Größe beträgt "compressedBufferSize" Byte, es können jedoch "1" B
yte gelesen werden. [C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\fuzzer\fuzzer.vcxproj]
C:\flan2\build\gtk\build\x64\release\lz4\tests\fuzzer.c(574): warning C26451: Arithmetischer Überlauf
: Wenn Sie den Operator "-" für einen 4-Bytewert verwenden und das Ergebnis in einen 8-Bytewert umwan
deln, wandeln Sie den Wert in den breiteren Typ um, bevor Sie den Operator "-" verwenden, um einen Üb
erlauf zu vermeiden (io.2). [C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\fuzzer\fuzzer.vcx
proj]
C:\flan2\build\gtk\build\x64\release\lz4\tests\fuzzer.c(574): warning C26451: Arithmetischer Überlauf
: Wenn Sie den Operator "<<" für einen 4-Bytewert verwenden und das Ergebnis in einen 8-Bytewert umwa
ndeln, wandeln Sie den Wert in den breiteren Typ um, bevor Sie den Operator "<<" verwenden, um einen
Überlauf zu vermeiden (io.2). [C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\fuzzer\fuzzer.v
cxproj]
C:\flan2\build\gtk\build\x64\release\lz4\tests\fuzzer.c(582): warning C26451: Arithmetischer Überlauf
: Wenn Sie den Operator "-" für einen 4-Bytewert verwenden und das Ergebnis in einen 8-Bytewert umwan
deln, wandeln Sie den Wert in den breiteren Typ um, bevor Sie den Operator "-" verwenden, um einen Üb
erlauf zu vermeiden (io.2). [C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\fuzzer\fuzzer.vcx
proj]
C:\flan2\build\gtk\build\x64\release\lz4\tests\fuzzer.c(582): warning C26451: Arithmetischer Überlauf
: Wenn Sie den Operator "<<" für einen 4-Bytewert verwenden und das Ergebnis in einen 8-Bytewert umwa
ndeln, wandeln Sie den Wert in den breiteren Typ um, bevor Sie den Operator "<<" verwenden, um einen
Überlauf zu vermeiden (io.2). [C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\fuzzer\fuzzer.v
cxproj]
C:\flan2\build\gtk\build\x64\release\lz4\tests\fuzzer.c(1551): warning C26451: Arithmetischer Überlau
f: Wenn Sie den Operator "-" für einen 4-Bytewert verwenden und das Ergebnis in einen 8-Bytewert umwa
ndeln, wandeln Sie den Wert in den breiteren Typ um, bevor Sie den Operator "-" verwenden, um einen Ü
berlauf zu vermeiden (io.2). [C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\fuzzer\fuzzer.vc
xproj]
C:\flan2\build\gtk\build\x64\release\lz4\tests\fuzzer.c(1551): warning C26451: Arithmetischer Überlau
f: Wenn Sie den Operator "-" für einen 4-Bytewert verwenden und das Ergebnis in einen 8-Bytewert umwa
ndeln, wandeln Sie den Wert in den breiteren Typ um, bevor Sie den Operator "-" verwenden, um einen Ü
berlauf zu vermeiden (io.2). [C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\fuzzer\fuzzer.vc
xproj]
C:\flan2\build\gtk\build\x64\release\lz4\tests\fuzzer.c(1607): warning C26451: Arithmetischer Überlau
f: Wenn Sie den Operator "+" für einen 4-Bytewert verwenden und das Ergebnis in einen 8-Bytewert umwa
ndeln, wandeln Sie den Wert in den breiteren Typ um, bevor Sie den Operator "+" verwenden, um einen Ü
berlauf zu vermeiden (io.2). [C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\fuzzer\fuzzer.vc
xproj]
C:\flan2\build\gtk\build\x64\release\lz4\tests\fuzzer.c(1608): warning C26451: Arithmetischer Überlau
f: Wenn Sie den Operator "+" für einen 4-Bytewert verwenden und das Ergebnis in einen 8-Bytewert umwa
ndeln, wandeln Sie den Wert in den breiteren Typ um, bevor Sie den Operator "+" verwenden, um einen Ü
berlauf zu vermeiden (io.2). [C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\fuzzer\fuzzer.vc
xproj]
C:\flan2\build\gtk\build\x64\release\lz4\tests\fuzzer.c(1609): warning C26451: Arithmetischer Überlau
f: Wenn Sie den Operator "+" für einen 4-Bytewert verwenden und das Ergebnis in einen 8-Bytewert umwa
ndeln, wandeln Sie den Wert in den breiteren Typ um, bevor Sie den Operator "+" verwenden, um einen Ü
berlauf zu vermeiden (io.2). [C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\fuzzer\fuzzer.vc
xproj]
C:\flan2\build\gtk\build\x64\release\lz4\tests\fuzzer.c(1610): warning C26451: Arithmetischer Überlau
f: Wenn Sie den Operator "+" für einen 4-Bytewert verwenden und das Ergebnis in einen 8-Bytewert umwa
ndeln, wandeln Sie den Wert in den breiteren Typ um, bevor Sie den Operator "+" verwenden, um einen Ü
berlauf zu vermeiden (io.2). [C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\fuzzer\fuzzer.vc
xproj]
  lz4.c
  lz4frame.c
  lz4hc.c
  xxhash.c
  fullbench.c
  Code Analysis für C/C++ wird ausgeführt...
  Code wird generiert.
  Previous IPDB not found, fall back to full compilation.
  All 193 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Codegenerierung ist abgeschlossen.
  fullbench.vcxproj -> C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\bin\x64_Release\fullben
  ch.exe
C:\flan2\build\gtk\build\x64\release\lz4\lib\lz4.c(489): warning C6385: Lesen ungültiger Daten von "v
":  die lesbare Größe beträgt "_Old_4`2" Byte, es können jedoch "4" Byte gelesen werden. [C:\flan2\bu
ild\gtk\build\x64\release\lz4\visual\vs2022\fullbench\fullbench.vcxproj]
  lz4.c
  lz4frame.c
  lz4hc.c
  xxhash.c
  frametest.c
  Code Analysis für C/C++ wird ausgeführt...
  Code wird generiert.
  Previous IPDB not found, fall back to full compilation.
  All 181 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Codegenerierung ist abgeschlossen.
  frametest.vcxproj -> C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\bin\x64_Release\framete
  st.exe
C:\flan2\build\gtk\build\x64\release\lz4\lib\lz4.c(489): warning C6385: Lesen ungültiger Daten von "v
":  die lesbare Größe beträgt "_Old_4`2" Byte, es können jedoch "4" Byte gelesen werden. [C:\flan2\bu
ild\gtk\build\x64\release\lz4\visual\vs2022\frametest\frametest.vcxproj]
  datagen.c
  datagencli.c
  Code Analysis für C/C++ wird ausgeführt...
  Code wird generiert.
  Previous IPDB not found, fall back to full compilation.
  All 10 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Codegenerierung ist abgeschlossen.
  datagen.vcxproj -> C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\bin\x64_Release\datagen.e
  xe
C:\flan2\build\gtk\build\x64\release\lz4\tests\datagencli.c(146): warning C26451: Arithmetischer Über
lauf: Wenn Sie den Operator "-" für einen 4-Bytewert verwenden und das Ergebnis in einen 8-Bytewert u
mwandeln, wandeln Sie den Wert in den breiteren Typ um, bevor Sie den Operator "-" verwenden, um eine
n Überlauf zu vermeiden (io.2). [C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\datagen\datag
en.vcxproj]
C:\flan2\build\gtk\build\x64\release\lz4\tests\datagencli.c(134): warning C26451: Arithmetischer Über
lauf: Wenn Sie den Operator "-" für einen 4-Bytewert verwenden und das Ergebnis in einen 8-Bytewert u
mwandeln, wandeln Sie den Wert in den breiteren Typ um, bevor Sie den Operator "-" verwenden, um eine
n Überlauf zu vermeiden (io.2). [C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\datagen\datag
en.vcxproj]
C:\flan2\build\gtk\build\x64\release\lz4\tests\datagencli.c(110): warning C26451: Arithmetischer Über
lauf: Wenn Sie den Operator "-" für einen 4-Bytewert verwenden und das Ergebnis in einen 8-Bytewert u
mwandeln, wandeln Sie den Wert in den breiteren Typ um, bevor Sie den Operator "-" verwenden, um eine
n Überlauf zu vermeiden (io.2). [C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\datagen\datag
en.vcxproj]
  xxhash.c
  fullbench.c
  Code Analysis für C/C++ wird ausgeführt...
  Code wird generiert.
  Previous IPDB not found, fall back to full compilation.
  All 49 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Codegenerierung ist abgeschlossen.
  fullbench-dll.vcxproj -> C:\flan2\build\gtk\build\x64\release\lz4\visual\vs2022\bin\x64_Release\ful
  lbench-dll.exe

Project(s) built:
    nuget                     (1.533 s)
    python                    (37.617 s)
    lz4                       (70.589 s)
```

### CODE REVIEW

**Comment by nacho** [comment]
I see a cmake project now in lz4. Shall we try instead of port the build to it? https://github.com/lz4/lz4/tree/dev/build/cmake

**Comment by danyeaw** [comment]
or maybe even meson? https://github.com/lz4/lz4/tree/dev/contrib/meson

**Comment by nacho** [comment]
+1 for meson :)

**Comment by danyeaw** [comment]
Thanks @iAnyKey for the contribution! This fixes the immediate issue, which is great, and then we can upgrade to meson in the future when their build setup fixes a few bugs.

**Pull request merged**
