### PR TITLE
Use appveyor to build gtk3 with VS2015

### PR DESCRIPTION
**Pull request by lazka**
https://ci.appveyor.com/project/lazka/gvsbuild/build/1.0.21

### CODE REVIEW

**Comment by nacho** [comment]
Thanks!

**Comment by lazka** [comment]
(you need to enable appveyor for this repo for things to work)

**Comment by nacho** [comment]
I have no idea about appveyor so I just added you to the org :)

**Comment by lazka** [comment]
ok, thanks, done :)

**Pull request merged**
