### PR TITLE
Add GTK3 to release artifacts

### LINKED ISSUE #1412: release more binaries
currently, only GTK4 with python 3.12 are being released as binaries.

why don't include all supported variants?
this means, all python (`3.8`-`3.12`) and both `GTK3` and `GTK4`.

this will help users to add it more easily.
in projects that require only some of the packages, the maintainer will compile it for the specific needs.

### PR DESCRIPTION
**Pull request by danyeaw**
Closes #1412 by adding release binaries for GTK3.

### CODE REVIEW

**Comment by pbor** [comment]
I am not opposed to this and I do not personally use the release artifacts used by our CI, however having everything in a single archive seems a bit weird: as a user how do I avoid shipping an unneeded version of gtk with my application? having to manually remove some of the dlls seems not great.

**Comment by danyeaw** [comment]
Hi @pbor, thanks for the feedback. There are two separate zip archives, one for GTK3 and one for GTK4.

**Comment by pbor** [comment]
> Hi @pbor, thanks for the feedback. There are two separate zip archives, one for GTK3 and one for GTK4.

Ah ok. I could not tell from just looking at the diff, sorry. Then sure, let's merge this.

**Review by pbor — APPROVED** [review]

**Comment by glyph** [comment]
\o/ thank you!

**Pull request merged**
