### PR TITLE
Update gstreamer and plugins, libjpeg-turbo, and Opus

### PR DESCRIPTION
**Pull request by danyeaw**
This PR moves Opus to use meson as well as updates gstreamer, gst plugins, and libjpeg-turbo.

I am not able to test gst-plugins-good, or update libyuv or libvpx because of #554.

### CODE REVIEW

**Comment by nacho** [comment]
I am a bit worried about using a version of opus that is not stable...

**Comment by danyeaw** [comment]
@nacho, since it is an audio codec and not a library with some breakage in APIs, I thought the risk was lower. X264 and Openh264 don't even have any releases. Opus also hasn't had a release in 3 years despite bug fixes and a new build system.

I am good with pulling the change out as well.

**Comment by nacho** [comment]
Oh! well, let's get it in

**Comment by nacho** [comment]
Thanks!

**Pull request merged**
