### PR TITLE
Update glib to version 2.72.1

### PR DESCRIPTION
**Pull request by danyeaw**

### CODE REVIEW

**Comment by nacho** [comment]
It fails because of the g-stat patch that was already merged in 2.72

**Comment by nacho** [comment]
We should also align glib-networking with this version

**Comment by pbor** [comment]
We may also want to wait a sec to understand https://gitlab.gnome.org/GNOME/glib/-/issues/2628

**Comment by danyeaw** [comment]
I updated the patches and glib-networkiing. I am not sure if we want to wait for that Inkscape issue to be resolved or not.

**Comment by nacho** [comment]
I would wait for 2.72.1

**Comment by danyeaw** [comment]
It looks like the fix to the issue above has been merged and backported to 2.72, now waiting on a new release.

**Pull request merged**
