### PR TITLE
Fix GLib scripts when Python path contains spaces

### LINKED ISSUE #1436: gdk-pixbuf fails to compile in CI
Looks like the latest version was pulled in my project in CI and it now doesn't compile:
```
Found ninja-1.12.1 at C:\gtk-build\tools\ninja-1.12.1\ninja.EXE
ninja: fatal: ReadFile: The handle is invalid.
[1/156] Generating glib marshaller header gdk-pixbuf/gdk-pixbuf-marshal_h

FAILED: gdk-pixbuf/gdk-pixbuf-marshal.h 

"C:\Program" "Files (x86)/pipx/venvs/gvsbuild/Scripts/python.exe" "C:/gtk-build/gtk/x64/release/bin/../bin/glib-genmarshal" "--quiet" "--prefix" "_gdk_pixbuf_marshal" "--output" "gdk-pixbuf/gdk-pixbuf-marshal.h" "--header" "../gdk-pixbuf/gdk-pixbuf-marshal.list" "--pragma-once"
CreateProcess failed: The system cannot find the file specified.
```

Looking at python path, it doesn't seem to be handling white spaces correctly.

CI logs: https://github.com/autonomys/space-acres/actions/runs/10834949725/job/30065354680?pr=294#step:6:16918

### PR DESCRIPTION
**Pull request by danyeaw**
Fixes #1436. The upstream issue is https://gitlab.gnome.org/GNOME/glib/-/issues/3331 and I opened https://gitlab.gnome.org/GNOME/glib/-/merge_requests/4391 to resolve it.

### CODE REVIEW

**Comment by nacho** [comment]
@danyeaw not clear to me from the comments in the issue. Shall we wait to have an agreement or do you still want to ship this?

**Comment by danyeaw** [comment]
Hi @nacho, I think the right solution is for upstream to create a new meson option, however, it doesn't seem like we have consensus yet. Should we merge some type of fix in the meantime?

**Comment by nacho** [comment]
Sure, go ahead

**Comment by danyeaw** [comment]
@nacho, thanks, could you give the PR an approval please?

**Review by nacho — APPROVED** [review]

**Pull request merged**
