### PR TITLE
Export the tarballs when building

### LINKED ISSUE #326: Properly create tarballs out of the projects
Right now we download the tarballs and put them in the src directory. In the case of the git repos we also create a tarball out of them.

I think we need the following:
 - we should have another directory i.e "tarballs"
 - the tarball expander should take the tarball from src and all the patches, zip it and put it in "tarballs"
 - the git repos should take the git repo without the .git folder and create a zip (should we just use git archive for this?), take this zip + the patches and create another zip

The reason is that in order to be compliant with the lgpl we need to provide the source code including any patch.

### PR DESCRIPTION
**Pull request by nacho**
And allow to choose the directory to export the tarballs
by default it is build-dir\export

Fixes #326

### CODE REVIEW

**Comment by nacho** [comment]
@guruDanny67 pinging you here to review it

**Comment by guruDanny67** [comment]
Start to check now. 

If the directory export doesn't exist an error is generated so, as for the other dirs, we have to create it at the beginning.

In the zip file you put only the patches but in my opinion we should put everything that's present in our patches dir: for example for cairo we have some makefile.win32.xxx files under build, the .pc files we install. 

For some other project we have the vs solution or the .vcxproj, modified (sometimes is easier put the new file directly that to make a patch).

A solution could be to make our modification and, at the end, create a single patch file that contains all the changes we made.

What do you think ?

Thanks

**Comment by guruDanny67** [comment]
Hi. 

There is a reason to use 'git archive' instead of using the already done zip file?
The difference is the case of the recorder file name (the zip has all in lowercase, but I fixed it because there's no need for it) and the third_part dir with the external projects (in the zip file are present, in the git archive not) that, imho, is better to have then not (is the exact situation of our built).

Thanks for your response.

**Comment by guruDanny67** [comment]
Hi, and first of all Happy new year, even if at least one month too late :)

There is some blocking change for merging this branch on the master line, I think it's really useful to help us (and everyone using some of these libraries) support and adhere to the various licenses of the projects: cleanup, make the libraries you need, copy the export dir in the installation disks/web site.

Maybe we should introduce a '-local' option of the script that doesn't download anything from the internet (.tar archives or git projects) but uses directly one dir with the downloaded files and in the end we save our script/patches and the download dir to give everyone the chance to install & build exactly the version we use.

Thank you in advance for your response.

   Daniele Forghieri

**Comment by nacho** [comment]
Ciao Daniele,

thanks for the comment. I think the local option is a good thing but it is actually orthogonal to what it is done here. Here what we try to achieve is a way to provide the tarballs with all the source we use so people can download it and build it if they wish. This is the tarball + patches or a snapshot of the git repo including the patches. I have been keeping the branch up to date because it is actually we are using on our end to get the tarballs to provide publicly.

Thanks

**Comment by guruDanny67** [comment]
We need this behavior for the same reason: we use some libraries (pango, cairo & librsvg, but it doesn't matter) and we need a good way to make public the source (with the patches!) of what we use.
I think that we can merge this branch (if you don't need/use this option you don't have worse performance or build time so it's ok as now) and then we can improve the situation (the --local option is useful by itself, especially when you're building & testing different configurations)

Thanks

**Comment by nacho** [comment]
I guess I missed your last comment :) I will merge it as it is so I stop having to rebase it over and over. Then we can improve it as we go.

**Pull request merged**
