### PR TITLE
Fix libpng fails to build with awk on path

### LINKED ISSUE #984: libpng fails to build
Command line (I'm doing this as I'm also trying to understand gvsbuild itself)
```
R:\src\test\gvsbuild>python gvsbuild\main.py build --ninja-opts -j=1 --build-dir r:\src\test\gvsbuild\build --msys-dir  r:\apps\msys64 --configuration debug libpng
```

Problem: `can't open source file R:/src/test/gvsbuild/build/build/x64/debug/libpng/_gvsbuild-cmake/scripts/checksym.awk`
But the file exists in one in the shadow(?) build folder: `R:\src\test\gvsbuild\build\build\x64\debug\libpng\scripts\checksym.awk`

Detail:
```
R:\src\test\gvsbuild>python gvsbuild\main.py build --ninja-opts -j=1 --build-dir r:\src\test\gvsbuild\build --msys-dir  r:\apps\msys64 --configuration debug libpng
...
Building project zlib (1.2.13)
(tar) Exporting libpng
Building project libpng (1.6.39)
CMake Deprecation Warning at CMakeLists.txt:13 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at CMakeLists.txt:14 (cmake_policy):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Configuring done (0.2s)
-- Generating done (0.1s)
-- Build files have been written to: R:/src/test/gvsbuild/build/build/x64/debug/libpng/_gvsbuild-cmake
[1/59] Generating scripts/symbols.chk
FAILED: scripts/symbols.chk R:/src/test/gvsbuild/build/build/x64/debug/libpng/_gvsbuild-cmake/scripts/symbols.chk
cmd.exe /C "cd /D R:\src\test\gvsbuild\build\build\x64\debug\libpng\_gvsbuild-cmake && R:\src\test\gvsbuild\build\tools\cmake-3.26.4-windows-x86_64\bin\cmake.exe -DINPUT=R:/src/test/gvsbuild/build/build/x64/debug/libpng/_gvsbuild-cmake/scripts/symbols.out -DOUTPUT=R:/src/test/gvsbuild/build/build/x64/debug/libpng/_gvsbuild-cmake/scripts/symbols.chk -P R:/src/test/gvsbuild/build/build/x64/debug/libpng/_gvsbuild-cmake/scripts/genchk.cmake"
gawk: fatal: can't open source file `R:/src/test/gvsbuild/build/build/x64/debug/libpng/_gvsbuild-cmake/scripts/checksym.awk' for reading (No such file or directory)
```

### PR DESCRIPTION
**Pull request by danyeaw**
Fixes #984.

The main change is submitted upstream here: https://github.com/pnggroup/libpng/pull/547, to disable use of awk with MSVC.

It is no longer required to move the Git\bin folder out of the way to get a successful build, so I removed that from the CI.

### CODE REVIEW

**Review by pbor — APPROVED** [review]

**Comment by pbor** [comment]
Nice!

**Comment by pbor** [comment]
I see actually that the upstream libpng has a different fix, so I guess we wait for that?

**Comment by danyeaw** [comment]
Hi @pbor, I updated the fix to match the one they are going to use upstream. I think it would still be worth patching this while we wait for the next version to come out.

**Review by pbor — APPROVED** [review]

**Comment by pbor** [comment]
Needs a small rebase... while you do that I guess we could just squash this in two commits:
1. the libpng update + patch
2. remove the git hack from ci

**Comment by danyeaw** [comment]
@pbor Thanks, good idea!

**Pull request merged**
