### PR TITLE
Fix missing stack.prop

### LINKED ISSUE #589: Error: Missing 'stack.prop'
Hello
I strictly followed the steps (with copy/paste), it all worked until the build, just after sending "gvsbuild build gtk3" or "gvsbuild build gtk4", I have the message:
`Error: Missing 'stack.prop' file on directory 'C:\gtk-build\github\gvsbuild\.venv\Scripts\gvsbuild.exe\patches'.
Wrong or missing --patches-root-dir option?`
Whatd did I do wrong, please?
Thanks
David

### PR DESCRIPTION
**Pull request by danyeaw**
Set the patches directory based on the build dir if it isn't set using `--patches-root-dir`. Fixes #589.

### CODE REVIEW

**Comment by nacho** [comment]
Any reason the ci is failing?

**Comment by danyeaw** [comment]
I am actually not sure. Things are working fine locally.

**Comment by danyeaw** [comment]
@nacho I figured it out. The previous fix was relying on the build_dir having a relationship to where the sources were checked out. I updated the PR to directly find the patches directory from the root of the project.

**Comment by nacho** [comment]
Cool

**Review by nacho — APPROVED** [review]

**Pull request merged**
