### PR TITLE
Update libffi to version 3.4.4

### PR DESCRIPTION
**Pull request by danyeaw**

### CODE REVIEW

**Comment by pbor** [comment]
Are we sure that the new fork is ready for production?

**Comment by danyeaw** [comment]
Yup. The fork is the main libtiff repo latest with a newly updated meson build system. There is also a PR to merge it back upstream. As is, it is better than the old fork we were using, hopefully soon we'll be able to use the official releases.

**Comment by pbor** [comment]
No super strong opinion, but it seems to me that the old fork is what gstreamer is also using for meson submodules etc, so it is probably much more tested. Maybe it is just naming, but I feel a bit better about using the gstreamer repo compared to a personal github branch that can go away at any time. If there us a chance of the PR being merged upstream, maybe we should wait for that to happen

**Comment by danyeaw** [comment]
This 3.2.9999.4 tag we are currently using seems very unofficial as well. I can close this, and we can wait for it to be merged upstream, or I could fork Xavier's fork if we are worried about it going away - I wasn't really worried about it since he is the Mr. Meson project converter after being the driving force behind getting GLib and Gstreamer converted.

**Comment by pbor** [comment]
I guess what I really meant is whether @xclaesse plans to push that branch to the gstreamer mirror... I know that 3.2.9999.4 is unofficial as well, but the gstreamer copy is used by people pulling gstreamer through meson submodules and thus a bit more tested.

Let's see if Xavier has an opinion, otherwise I guess I am ok with this patch

**Comment by xclaesse** [comment]
It is true that 3.2.9999.4 GStreamer fork is probably more tested, but it is an unofficial fork, including code changes. My branch is only adding meson build definition on top of upstream libffi, without any code changes. I wanted to wait for upstream to review/merge before moving GStreamer to this version of libffi, but since maintainers are really busy I'll probably submit my Meson port to Meson's WrapDB and move GStreamer to it.

In any cases, getting it into gvsbuild would give us more feedback on the new port quality, that would be appreciated :)

**Pull request merged**
