### PR TITLE
Fix Visual Studio version search

### PR DESCRIPTION
**Pull request by KyleSiefring**
Prevents vs2017 from being used when version 17 (2022) is specified.

### CODE REVIEW

**Comment by danyeaw** [comment]
Hi @KyleSiefring, thanks for the contribution. Could you please explain more about the issue? What is your setup and what does this fix?

**Comment by KyleSiefring** [comment]
I have both the Visual Studio 2017 (version number 15.x) build tools installed and Visual Studio 2022 (version number 17.x) installed. The problem is that 2017 shows up in the list passed to this function before 2022. In that case, if we search for version 17 (again 2022), we end up selecting the 2017 edition based on the path.

Here are the current editions (year) and version number pairs.
https://github.com/wingtk/gvsbuild/blob/240dc5b6e600b45dfdbdd38b2dd23b7cedd1dd4f/gvsbuild/utils/builder.py#L98

**Comment by danyeaw** [comment]
Thanks! Can you please run `pre-commit install` and `pre-commit run --all-files` to fix the lint issues Ruff detected?

**Review by danyeaw — APPROVED** [review]
Thanks for the contribution @KyleSiefring!

**Pull request merged**
