### PR TITLE
Update gettext to version 0.21.1

### PR DESCRIPTION
**Pull request by danyeaw**

### CODE REVIEW

**Comment by danyeaw** [comment]
We are going to have to repatch gettext for this one.

**Comment by nacho** [comment]
Gettext is always a major pain. We need to check if the repo from @fanc999 is having the patches for this new version

**Comment by danyeaw** [comment]
Since this is going to require a lot of patching, I am going to close this for now. I also submitted https://github.com/mesonbuild/wrapdb/issues/773, maybe we could work together to wrap gettext meson build setup.

**Comment by danyeaw** [comment]
Thanks @fanc999!

**Comment by fanc999** [comment]
Hi,

The build for the items in `gettext-tools` are now ready in my branch.  No install target though for now, just a good run to build the libraries, the C# items (with Visual C#) and the tools in `gettext-runtime` and `gettext-tools`.

**Pull request closed without merging**
